### ISSUE TITLE
Potential bug in `find_illumination_pattern2`

### ISSUE THREAD

**Issue by lanceXwq** [Cao-ruijie/Open3DSIM#2]
Hello,

I ran into an error running Open3DSIM earlier. It seems that in `find_illumination_pattern2` the variable/function `phase` is never defined, see [here](https://github.com/Cao-ruijie/Open3DSIM/blob/e1a808e05c5869b891b0e778be6874756912fd5f/MATLAB_Open_3DSIM/help_functions/find_illumination_pattern2.m#L96). Is this a bug or have I done something incorrectly?

Thank you!

**Comment by Cao-ruijie** [comment]
Dear Xu:
    It's may be because of the different version of MATLAB. "phase" function is to resolve the angle of a vector. You can change "phase" into "angle" to solve this problem.
    Hope this can resolve your problem.
 
Best regards,
Ruijie Cao 

Ph. D. Candidate 
College of Future Technology, Peking University
Tel: +86  18625161696
Email: ***@***.***





发件人："Lance (Weiqing) Xu" ***@***.***>
发送日期：2024-03-19 01:53:56
收件人：Cao-ruijie/Open3DSIM ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[Cao-ruijie/Open3DSIM] Potential bug in `find_illumination_pattern2` (Issue #2)

Hello,
I ran into an error running Open3DSIM earlier. It seems that in find_illumination_pattern2 the variable/function phase is never defined, see here. Is this a bug or have I done something incorrectly?
Thank you!

**Comment by lanceXwq** [comment]
Thanks, Rujie. I will ask my colleague to give it a try!
